/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.EmpleadoDAO;
import datos.CandidatoDAO;
import datos.RondaVotosDAO;
import domain.Empleado;
import domain.Candidato;
import domain.RondaVotos;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.Random;

/**
 *
 * @author visitante
 */
public class VotacionesResultado extends javax.swing.JInternalFrame {

    public void llenadoDeCombos() {
        CandidatoDAO candidatoDAO = new CandidatoDAO();
        List<Candidato> candidatos = candidatoDAO.select();
        ComboBoxCandidatos1.addItem("Seleccione una opción");
        ComboBoxCandidatos2.addItem("Seleccione una opción");
        ComboBoxCandidatos3.addItem("Seleccione una opción");
        for (int i = 0; i < candidatos.size(); i++) {
            ComboBoxCandidatos1.addItem(candidatos.get(i).getNombreCandidato());
            ComboBoxCandidatos2.addItem(candidatos.get(i).getNombreCandidato());
            ComboBoxCandidatos3.addItem(candidatos.get(i).getNombreCandidato());
        }
    }
    
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Candidato");
        modelo.addColumn("Nombre Candidato");
        modelo.addColumn("Primera Ronda");
        modelo.addColumn("Segunda Ronda");
        modelo.addColumn("Tercera Ronda");
        modelo.addColumn("Cuarta Ronda");
        modelo.addColumn("Quinta Ronda");
        modelo.addColumn("Votos Totales");
        RondaVotosDAO rondaVotosDAO = new RondaVotosDAO();
        List<RondaVotos> rondaVotos = rondaVotosDAO.select();
        tablaVotos.setModel(modelo);
        String[] dato = new String[8];
        for (int i = 0; i < rondaVotos.size(); i++) {
            dato[0] = Integer.toString(rondaVotos.get(i).getIdRondavotos());
            dato[1] = rondaVotos.get(i).getNombreCandidato();
            dato[2] = Integer.toString(rondaVotos.get(i).getRondaUno());
            dato[3] = Integer.toString(rondaVotos.get(i).getRondaDos());
            dato[4] = Integer.toString(rondaVotos.get(i).getRondaTres());
            dato[5] = Integer.toString(rondaVotos.get(i).getRondaCuatro());
            dato[6] = Integer.toString(rondaVotos.get(i).getRondaCinco());
            dato[7] = Integer.toString(rondaVotos.get(i).getRondaTotal());
            modelo.addRow(dato);
        }
    }
    
    /*public void buscarVendedor() {
        Candidato candidatoAConsultar = new Candidato();
        CandidatoDAO candidatoDAO = new CandidatoDAO();
        candidatoAConsultar.setIdCandidato(Integer.parseInt(txtbuscado.getText()));
        candidatoAConsultar = candidatoDAO.query(candidatoAConsultar);
        txtNombre.setText(candidatoAConsultar.getNombreCandidato());
        txtStatus.setText(candidatoAConsultar.getEstatusCandidato());
    }*/

    public VotacionesResultado() {
        initComponents();
        llenadoDeTablas();
        llenadoDeCombos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtbuscado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVotos = new javax.swing.JTable();
        ComboBoxCandidatos1 = new javax.swing.JComboBox<>();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ComboBoxCandidatos2 = new javax.swing.JComboBox<>();
        ComboBoxCandidatos3 = new javax.swing.JComboBox<>();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtN3 = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        txtN4 = new javax.swing.JTextField();
        txtN5 = new javax.swing.JTextField();
        txtN6 = new javax.swing.JTextField();
        txtN7 = new javax.swing.JTextField();
        txtN8 = new javax.swing.JTextField();
        txtN9 = new javax.swing.JTextField();
        txtN10 = new javax.swing.JTextField();
        txtN11 = new javax.swing.JTextField();
        txtN12 = new javax.swing.JTextField();
        txtN13 = new javax.swing.JTextField();
        txtN14 = new javax.swing.JTextField();
        txtN15 = new javax.swing.JTextField();
        txtR1 = new javax.swing.JTextField();
        txtR2 = new javax.swing.JTextField();
        txtR3 = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        btnRegistrar1 = new javax.swing.JButton();
        btnRegistrar2 = new javax.swing.JButton();
        label12 = new javax.swing.JLabel();
        ganador = new javax.swing.JTextField();
        btnDeterminar = new javax.swing.JButton();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Candidatos");
        setVisible(true);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar Ronda");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaVotos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Ronda", "Candidato", "Ronda 1", "Ronda 2", "Ronda 3", "Ronda 4", "Ronda 5", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVotos);

        ComboBoxCandidatos1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ComboBoxCandidatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCandidatos1ActionPerformed(evt);
            }
        });

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR1ActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("Ronda 1");

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("Ronda 2");

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("Ronda 3");

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("Ronda 4");

        label10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label10.setText("Ronda 5");

        label11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label11.setText("Totales");

        btnRegistrar1.setText("Registrar Ronda");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        btnRegistrar2.setText("Registrar Ronda");
        btnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar2ActionPerformed(evt);
            }
        });

        label12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label12.setText("El ganador es:");

        ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganadorActionPerformed(evt);
            }
        });

        btnDeterminar.setText("Determinar Ganador");
        btnDeterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeterminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ComboBoxCandidatos1, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                        .addComponent(ComboBoxCandidatos2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxCandidatos3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(btnGenerar)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtN5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtN3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtN6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label7)
                                            .addComponent(txtN4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtN7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(txtN8)
                                        .addComponent(txtN9))
                                    .addComponent(label8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtN11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(txtN10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtN12)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtN13)
                                .addComponent(txtN14)
                                .addComponent(txtN15, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addComponent(label10))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtR1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                                .addComponent(txtR2)
                                                .addComponent(txtR3))
                                            .addComponent(label12))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnRegistrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnDeterminar)))
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label6)
                        .addComponent(label7)
                        .addComponent(label8)
                        .addComponent(label9)
                        .addComponent(label10)
                        .addComponent(label11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCandidatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCandidatos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCandidatos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label12)
                            .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDeterminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar))
                        .addGap(40, 40, 40))))
        );

        btnModificar.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        RondaVotosDAO rondaVotosDAO = new RondaVotosDAO();
        RondaVotos votosoAEliminar = new RondaVotos();
        votosoAEliminar.setIdRondavotos(Integer.parseInt(txtbuscado.getText()));
        rondaVotosDAO.delete(votosoAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String valorSeleccionado = ComboBoxCandidatos1.getSelectedItem().toString();
        RondaVotosDAO rondaVotosDAO = new RondaVotosDAO();
        RondaVotos votosAInsertar = new RondaVotos();
        votosAInsertar.setNombreCandidato(valorSeleccionado);
        votosAInsertar.setRondaUno(Integer.parseInt(txtN1.getText()));
        votosAInsertar.setRondaDos(Integer.parseInt(txtN4.getText()));
        votosAInsertar.setRondaTres(Integer.parseInt(txtN7.getText()));
        votosAInsertar.setRondaCuatro(Integer.parseInt(txtN10.getText()));
        votosAInsertar.setRondaCinco(Integer.parseInt(txtN13.getText()));
        votosAInsertar.setRondaTotal(Integer.parseInt(txtR1.getText()));
        rondaVotosDAO.insert(votosAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //buscarVendedor();
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
        /*CandidatoDAO candidatoDAO = new CandidatoDAO();
        Candidato candidatoAActualizar = new Candidato();
        candidatoAActualizar.setIdCandidato(Integer.parseInt(txtbuscado.getText()));
        candidatoAActualizar.setNombreCandidato(txtNombre.getText());
        candidatoAActualizar.setEstatusCandidato(txtStatus.getText());
        candidatoDAO.update(candidatoAActualizar);
        llenadoDeTablas();*/
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtbuscado.setText("");
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnDeterminar.setEnabled(true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void ComboBoxCandidatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCandidatos1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCandidatos1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public int[] generarNumerosAleatorios(int sumtotal, int divVotos) {
        Random rand = new Random();
        int[] votos = new int[divVotos];

        int[] restaCompl = new int[divVotos - 1];
        for (int i = 0; i < restaCompl.length; i++) {
            restaCompl[i] = rand.nextInt(sumtotal + 1);
        }
        java.util.Arrays.sort(restaCompl);

        votos[0] = restaCompl[0];
        for (int i = 1; i < restaCompl.length; i++) {
            votos[i] = restaCompl[i] - restaCompl[i - 1];
        }
        votos[divVotos - 1] = sumtotal - restaCompl[restaCompl.length - 1];

        return votos;
    }
    
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int sumtotal = 50, v1, v2, v3;
        int divVotos = 3;
        
        
        int[] ronda1 = generarNumerosAleatorios(sumtotal, divVotos);
        txtN1.setText(String.valueOf(ronda1[0]));
        txtN2.setText(String.valueOf(ronda1[1]));
        txtN3.setText(String.valueOf(ronda1[2]));
        
        int[] ronda2 = generarNumerosAleatorios(sumtotal, divVotos);
        txtN4.setText(String.valueOf(ronda2[0]));
        txtN5.setText(String.valueOf(ronda2[1]));
        txtN6.setText(String.valueOf(ronda2[2]));

        int[] ronda3 = generarNumerosAleatorios(sumtotal, divVotos);
        txtN7.setText(String.valueOf(ronda3[0]));
        txtN8.setText(String.valueOf(ronda3[1]));
        txtN9.setText(String.valueOf(ronda3[2]));
        
        int[] ronda4 = generarNumerosAleatorios(sumtotal, divVotos);
        txtN10.setText(String.valueOf(ronda4[0]));
        txtN11.setText(String.valueOf(ronda4[1]));
        txtN12.setText(String.valueOf(ronda4[2]));
        
        int[] ronda5 = generarNumerosAleatorios(sumtotal, divVotos);
        txtN13.setText(String.valueOf(ronda5[0]));
        txtN14.setText(String.valueOf(ronda5[1]));
        txtN15.setText(String.valueOf(ronda5[2]));
        
        int suma1 = Integer.parseInt(txtN1.getText()) + Integer.parseInt(txtN4.getText()) + Integer.parseInt(txtN7.getText()) + Integer.parseInt(txtN10.getText()) + Integer.parseInt(txtN13.getText());
        int suma2 = Integer.parseInt(txtN2.getText()) + Integer.parseInt(txtN5.getText()) + Integer.parseInt(txtN8.getText()) + Integer.parseInt(txtN11.getText()) + Integer.parseInt(txtN14.getText());
        int suma3 = Integer.parseInt(txtN3.getText()) + Integer.parseInt(txtN6.getText()) + Integer.parseInt(txtN9.getText()) + Integer.parseInt(txtN12.getText()) + Integer.parseInt(txtN15.getText());
        
        txtR1.setText(String.valueOf(suma1));
        txtR2.setText(String.valueOf(suma2));
        txtR3.setText(String.valueOf(suma3));
        
        label6.setVisible(true);
        label7.setVisible(true);
        label8.setVisible(true);
        label9.setVisible(true);
        label10.setVisible(true);
        label11.setVisible(true);
       
        
        

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        String valorSeleccionado = ComboBoxCandidatos2.getSelectedItem().toString();
        RondaVotosDAO rondaVotosDAO = new RondaVotosDAO();
        RondaVotos votosAInsertar = new RondaVotos();
        votosAInsertar.setNombreCandidato(valorSeleccionado);
        votosAInsertar.setRondaUno(Integer.parseInt(txtN2.getText()));
        votosAInsertar.setRondaDos(Integer.parseInt(txtN5.getText()));
        votosAInsertar.setRondaTres(Integer.parseInt(txtN8.getText()));
        votosAInsertar.setRondaCuatro(Integer.parseInt(txtN11.getText()));
        votosAInsertar.setRondaCinco(Integer.parseInt(txtN14.getText()));
        votosAInsertar.setRondaTotal(Integer.parseInt(txtR2.getText()));
        rondaVotosDAO.insert(votosAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar2ActionPerformed
        String valorSeleccionado = ComboBoxCandidatos3.getSelectedItem().toString();
        RondaVotosDAO rondaVotosDAO = new RondaVotosDAO();
        RondaVotos votosAInsertar = new RondaVotos();
        votosAInsertar.setNombreCandidato(valorSeleccionado);
        votosAInsertar.setRondaUno(Integer.parseInt(txtN3.getText()));
        votosAInsertar.setRondaDos(Integer.parseInt(txtN6.getText()));
        votosAInsertar.setRondaTres(Integer.parseInt(txtN9.getText()));
        votosAInsertar.setRondaCuatro(Integer.parseInt(txtN12.getText()));
        votosAInsertar.setRondaCinco(Integer.parseInt(txtN15.getText()));
        votosAInsertar.setRondaTotal(Integer.parseInt(txtR3.getText()));
        rondaVotosDAO.insert(votosAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrar2ActionPerformed

    private void txtR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR1ActionPerformed

    private void ganadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganadorActionPerformed

    private void btnDeterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeterminarActionPerformed
       
        String resulGanador;
    int suma1 = Integer.parseInt(txtN1.getText()) + Integer.parseInt(txtN4.getText()) + Integer.parseInt(txtN7.getText()) + Integer.parseInt(txtN10.getText()) + Integer.parseInt(txtN13.getText());
    int suma2 = Integer.parseInt(txtN2.getText()) + Integer.parseInt(txtN5.getText()) + Integer.parseInt(txtN8.getText()) + Integer.parseInt(txtN11.getText()) + Integer.parseInt(txtN14.getText());
    int suma3 = Integer.parseInt(txtN3.getText()) + Integer.parseInt(txtN6.getText()) + Integer.parseInt(txtN9.getText()) + Integer.parseInt(txtN12.getText()) + Integer.parseInt(txtN15.getText());

    txtR1.setText(String.valueOf(suma1));
    txtR2.setText(String.valueOf(suma2));
    txtR3.setText(String.valueOf(suma3));

    if (suma1 > suma2 && suma1 > suma3) {
        resulGanador = ComboBoxCandidatos1.getSelectedItem().toString();
    } else if (suma2 > suma1 && suma2 > suma3) {
        resulGanador = ComboBoxCandidatos2.getSelectedItem().toString();
    } else if (suma3 > suma1 && suma3 > suma2) {
        resulGanador = ComboBoxCandidatos3.getSelectedItem().toString();
    } else {
        resulGanador = "Empate"; 
    }
     label12.setVisible(true);
     
    // Mostrar el ganador en un label o en la consola
    ganador.setText( resulGanador);

    }//GEN-LAST:event_btnDeterminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCandidatos1;
    private javax.swing.JComboBox<String> ComboBoxCandidatos2;
    private javax.swing.JComboBox<String> ComboBoxCandidatos3;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeterminar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JButton btnRegistrar2;
    private javax.swing.JTextField ganador;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVotos;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN10;
    private javax.swing.JTextField txtN11;
    private javax.swing.JTextField txtN12;
    private javax.swing.JTextField txtN13;
    private javax.swing.JTextField txtN14;
    private javax.swing.JTextField txtN15;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    private javax.swing.JTextField txtN4;
    private javax.swing.JTextField txtN5;
    private javax.swing.JTextField txtN6;
    private javax.swing.JTextField txtN7;
    private javax.swing.JTextField txtN8;
    private javax.swing.JTextField txtN9;
    private javax.swing.JTextField txtR1;
    private javax.swing.JTextField txtR2;
    private javax.swing.JTextField txtR3;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
